/**
 * Test Attachment Upload
 * Simple script to test uploading text attachments to IETM
 */

import { IETMClient } from '../src/client/IETMClient';
import { AttachmentHandler } from '../src/attachments/AttachmentHandler';
import { loadConfig } from '../src/config/ConfigManager';

async function testAttachmentUpload() {
  console.log('='.repeat(80));
  console.log('Testing IETM Attachment Upload');
  console.log('='.repeat(80));
  console.log('');

  try {
    // Load configuration
    console.log('1. Loading configuration...');
    const config = loadConfig('config/ietm.config.json');
    console.log('   ✓ Configuration loaded');
    console.log('');

    // Initialize IETM client
    console.log('2. Initializing IETM client...');
    
    // Extract username and password from auth config
    let username = '';
    let password = '';
    if (config.auth.type === 'basic') {
      username = config.auth.username;
      password = config.auth.password;
    }
    
    const clientConfig = {
      qmServerUrl: config.server.baseUrl,
      jtsServerUrl: config.server.jtsUrl || config.server.baseUrl.replace('/qm', '/jts'),
      username,
      password,
      projectName: config.server.projectName || config.server.projectId || '',
      projectArea: config.server.projectId || config.server.projectName || '',
    };
    const client = new IETMClient(clientConfig);
    await client.initialize();
    console.log('   ✓ Client initialized');
    console.log('');

    // Create attachment handler
    console.log('3. Creating attachment handler...');
    const attachmentHandler = new AttachmentHandler(client);
    console.log('   ✓ Attachment handler created');
    console.log('');

    // Prepare test output
    const testOutput = `
=================================================================================
Test: Sample Login Test
Status: passed
Duration: 1234ms
Started: ${new Date().toISOString()}
=================================================================================

Location: tests/login.spec.ts:10:5

STEPS:
---------------------------------------------------------------------------------
1. Navigate to login page
   Duration: 234ms
2. Enter username
   Duration: 123ms
3. Enter password
   Duration: 145ms
4. Click login button
   Duration: 456ms
5. Verify dashboard loaded
   Duration: 276ms
---------------------------------------------------------------------------------

STDOUT:
---------------------------------------------------------------------------------
[Playwright] Starting test execution
[Playwright] Browser: chromium
[Playwright] Viewport: 1280x720
---------------------------------------------------------------------------------

=================================================================================
Generated by IETM Playwright Reporter at ${new Date().toISOString()}
=================================================================================
`;

    // Upload test output
    console.log('4. Uploading test output as attachment...');
    console.log(`   Test name: Sample Login Test`);
    console.log(`   Output size: ${testOutput.length} characters`);
    console.log('');
    
    // Use a test execution result ID (you can replace with actual ID)
    const executionResultId = 'urn:com.ibm.rqm:executionresult:2892';
    
    const attachmentUrl = await attachmentHandler.uploadTestOutput(
      testOutput,
      'Sample_Login_Test',
      executionResultId
    );

    if (attachmentUrl) {
      console.log('   ✓ Attachment uploaded successfully!');
      console.log(`   URL: ${attachmentUrl}`);
      console.log('');
      console.log('='.repeat(80));
      console.log('SUCCESS: Attachment upload test completed');
      console.log('='.repeat(80));
    } else {
      console.error('   ✗ Failed to upload attachment');
      console.log('');
      console.log('='.repeat(80));
      console.log('FAILED: Attachment upload returned null');
      console.log('='.repeat(80));
      process.exit(1);
    }

  } catch (error) {
    console.error('');
    console.error('='.repeat(80));
    console.error('ERROR: Attachment upload test failed');
    console.error('='.repeat(80));
    console.error(error);
    process.exit(1);
  }
}

// Run the test
testAttachmentUpload().catch(error => {
  console.error('Unhandled error:', error);
  process.exit(1);
});

// Made with Bob
